name: KTSPvPManager
main: net.jp.kts.syuuryan.KTSPvPManager
version: 1.2.0
default-permission: NOT_OP
commands:
    chat:
        description: チームに属している時、チャットモードを切り替えます。
        permission: KTSPvPManager.chat
        permission-message: コマンドの権限が与えられていません。
        usage: チームに属していません。
    pvp:
        description: PvPに関するコマンド
        permission: KTSPvPManager.pvp
        permission-message: コマンドの権限が与えられていません。
        usage: "Usage: /pvp [team | ff | fv]"
permissions:
    chat.*:
        description:
        default: true
    pvp.*:
        description:
        default: true
        children:
            pvp.team.add: true
            pvp.team.join: true
            pvp.team.leave: true
            pvp.team.empty: true
            pvp.team.remove: true
            pvp.team.clear: true
            pvp.team.list: true
            pvp.ff: true
            pvp.fv: true
    pvp.team.add:
        description: チームの作成を許可します
        default: true
    pvp.team.join:
        description: チームへのプレイヤー参加を許可します
        default: true
    pvp.team.leave:
        description: チームへのプレイヤー削除を許可します
        default: true
    pvp.team.empty:
        description: チームへのプレイヤー全削除を許可します
        default: true
    pvp.team.remove:
        description: チームの削除を許可します
        default: true
    pvp.team.clear:
        description: チームの全削除を許可します
        default: true
    pvp.team.list:
        description: チームリストの閲覧を許可します
        default: true
    pvp.ff:
        description: フレンドリファイアの設定を許可します
        default: true
    pvp.fv:
        description: チーム内透明ポーション可視化の設定を許可します
        default: true